
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'jaffle_shop'
version: '1.5.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

seeds:
  jaffle_shop:
    +schema: seed_data


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  jaffle_shop:
    +database: analytics
    cert:
      +schema: cert
      +materialized: view
    staging:
      jaffle_shop:
        +schema: staging
        +materialized: view
      stripe:
        +schema: staging
        +materialized: view
    marts:
      core:
        +schema: marts
        +materialized: table
        +required_tests: {"unique.*|not_null": 1}

# ======
# Snapshot Configs
# ======
snapshots:
  jaffle_shop:
    +target_database: analytics
    +target_schema: cert


tests:
  jaffle_shop:  # project name
    staging:    # top-level dir inside models/ dir
      +store_failures: true
      +schema: dbt_test
      jaffle_shop:
        +limit: 10
        +store_failures: true
        +schema: dbt_test

vars:
  # The `start_date` variable will be accessible in all resources
  start_date: '2022-06-01'
  # The `platforms` variable is only accessible to resources in the jaffle_shop project
  jaffle_shop:
    platforms: ['web', 'mobile']
